### ISSUE TITLE
Version 2.x not available

### ISSUE THREAD

**Issue by markmatney** [usnistgov/OpenSeadragonScalebar#4]
I am unable to find the 2.x release that is compatible with OSD 2, as mentioned in the README. It is not under `releases`, nor is there a commit that mentions it. Can someone help?

**Comment by avandecreme** [comment]
Sorry, there isn't really a release for 2.x but the master branch is compatible with OSD 2.

**Comment by markmatney** [comment]
Great, thanks for the info.
